language: python

python:
  - "3.5"

install:
  # To work around a problem with wilson package we take the git master version of it
  - "pip3 install ."
  - "pip3 install nose2"
  - "pip3 install coveralls"

script: 
  - "nose2 --with-coverage"

after_success: coveralls
